services:
  app:
    container_name: app
    build: .
    pull_policy: never
    ports:
      - 8080:8080
  redis:
    container_name: redis
    image: redis:7.4.1
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --appendonly no
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:2.58
    ports:
      - 5540:5540
    volumes:
      - redisinsight:/data
  postgres:
    container_name: postgres
    image: postgres:16.4
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8.12.0
    container_name: pgadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  redisinsight:
  redis:
  postgres:
  pgadmin: